name: Backend - Build and Push Tag
on:
  push:
    tags:
      - '*\/[0-9]+.[0-9]+.[0-9]+**'
      - "!admin/*"
      - "!frontend-vo/*"

jobs:
  build:
    name: ⚙️ Docker Build, Tag, and Push
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Get git Tag
        id: git_tag
        run: |
          echo APP_NAME=$(echo ${GITHUB_REF#refs/tags/} | grep -oP "^[a-z-]+") >> $GITHUB_OUTPUT
          echo GIT_TAG=$(echo ${GITHUB_REF#refs/tags/} | grep -oP "[0-9]+.[0-9]+.[0-9]+.*") >> $GITHUB_OUTPUT
          echo GIT_HASH=$(echo ${{ github.sha }} | cut -c 1-8) >> $GITHUB_OUTPUT
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/${{ steps.git_tag.outputs.APP_NAME }}/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Tag and Push Version Tag
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          build-args: |
            APP_NAME=${{ steps.git_tag.outputs.APP_NAME }}
            GIT_HASH=${{ steps.git_tag.outputs.GIT_HASH }}
            GIT_TAG=${{ steps.git_tag.outputs.GIT_TAG }}
          tags: ${{ secrets.DOCKER_REGISTRY_URL }}/${{ steps.git_tag.outputs.APP_NAME }}:${{ steps.git_tag.outputs.GIT_TAG }}
          cache-from: type=local,src=/tmp/${{ steps.git_tag.outputs.APP_NAME }}/.buildx-cache
          cache-to: type=local,dest=/tmp/${{ steps.git_tag.outputs.APP_NAME }}/.buildx-cache-new,mode=max
      - name: Move cache
        run: |
          rm -rf /tmp/${{ steps.git_tag.outputs.APP_NAME }}/.buildx-cache
          mv /tmp/${{ steps.git_tag.outputs.APP_NAME }}/.buildx-cache-new /tmp/${{ steps.git_tag.outputs.APP_NAME }}/.buildx-cache
