name: Code Quality and Tests
on:
  pull_request:

jobs:
  dep-check:
    name: '✅ Check Dependencies'
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install and check dependencies
        run: |
          npm ci
          npm run deps:check

  lint:
    name: "✅ Lint"
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Install dependencies and lint
        run: |
          npm ci
          npm run lint

  unit-tests:
    name: "🧪 Unit Test"
    needs:
      - lint
      - dep-check
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Install dependencies and run tests
        run: |
          npm ci
          npm run test:unit
  e2e-tests:
    name: "🧪 E2E Tests Test"
    needs:
      - lint
      - dep-check
    runs-on: ubuntu-latest
    env:
      CI: true
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: appcompass_test
          POSTGRES_PASSWORD: testPassword
          POSTGRES_DB: appcompass_test
          POSTGRES_PORT: 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Install dependencies and run end-to-end tests
        run: |
          npm ci
          npm run test:e2e
